language: python
sudo: false
dist: trusty

deploy:
  provider: pypi
  user: hmaarrfk
  password:
    secure: jTn4X7JqUJqgEQ/j4n6u/Lsmks07sWGj6ErG/8XVQdTLLdu4nwYQusO+PQV9+fyEoWRFCytjdnVQ9QMeIVmA7AmtYIsNF3k1VYKbYu3gsqlFUhNI2ck9eQDUbmqjEIAiaC21jixsq02d9HRWNdSPYhtXCBKTy+fce33m2bXMVDu6QPZpQ97mRT7kGcwRPesVfxRJFElvfeiTCJPfqwyqfwrqx6VGaYAz6CxQelBZRy0O3T9fnDipfscfa7u+DQv3dx3/sft0LLRhM9Ths/zTvdj1vIHuXrrA6O5JW9oSdfYpuugu+Xm/UuOr76cY5MtyOwJaRa1vPB6T83x9X9HwF4C58hZmpezcNg2x3df4R3KJt/IOg30kT64+DuDW70pnfGhm2UP9fczTsJ/bBw6Rgwe8oz1TXBntYSMzRui8IXed/Noudy/rdXQH17HwJ3ICUMID+IRqxYngHt17NOeffR4TeqSI51fYDRI3iiFZOtJoGoWT8cy6/Xj2jaop053AQysB3soErquM0T851TpmJc+FoSb6jrWI3TG8/+uqGFpWmhfqKPu5Wf7RiVYYeZLOzVRmN3LHb3XVlm1+7m/80bYI2NSQnuOviH2WW+ePT5oqn+YIfgmSewlvrNwEoohM3T2sN9DPH8oyGYehQFXd2T3v+9FMBYHpeduL7dSPvVw=
  distributions: "sdist bdist_wheel"
